#!python3

# Generates the /chapters, /pygame/chapters, and /hacking/chapters pages from source data.


inventData = [{'name': 'Installing Python',
               'videos': [{'name': 'Installing Python on Windows', 'url': 'http://www.youtube-nocookie.com/embed/4Mf0h3HphEA'},
                          {'name': 'Installing Python 3.1 under MacOSX', 'url': 'http://www.youtube-nocookie.com/embed/MEmEJCLLI2k'},
                          {'name': 'Install Python 3.1 using Linux', 'url': 'http://www.youtube-nocookie.com/embed/RLPYBxfAud4'}],
                          },
            {'name': 'The Interactive Shell'},
            {'name': 'Strings',
             'programs': ['hello.py']},
            {'name': 'Guess the Number',
             'programs': ['guess.py']},
            {'name': 'Jokes',
             'programs': ['jokes.py']},
            {'name': 'Dragon Realm',
             'programs': ['dragon.py']},
            {'name': 'Using the Debugger'},
            {'name': 'Flow Charts'},
            {'name': 'Hangman',
             'programs': ['hangman.py']},
            {'name': 'Tic Tac Toe',
             'programs': ['tictactoe.py']},
            {'name': 'Bagels',
             'programs': ['bagels.py']},
            {'name': 'Cartesian Coordinates'},
            {'name': 'Sonar',
             'programs': ['sonar.py']},
            {'name': 'Caesar Cipher',
             'programs': ['cipher.py']},
            {'name': 'Reversi',
             'programs': ['reversi.py']},
            {'name': 'AI Simulation',
             'programs': ['AISim1.py', 'AISim2.py', 'AISim3.py']},
            {'name': 'Graphics and Animation',
             'programs': ['pygameHelloWorld.py'],
             'videos': [{'name': 'Installing Pygame on Windows', 'url': 'http://www.youtube-nocookie.com/embed/0xgn-HKzZes'}]},
            {'name': 'Collision Detection and Input',
             'programs': ['collisionDetection.py', 'pygameInput.py']},
            {'name': 'Sounds and Images',
             'programs': ['spritesAndSounds.py'],
             'downloads': ['cherry.png', 'player.png', 'background.mid', 'pickup.wav']},
            {'name': 'Dodger',
             'programs': ['dodger.py'],
             'downloads': ['baddie.png', 'player.png', 'background.mid', 'gameover.wav']}
             ]

pygameData = [{'name': 'Installing Python'},
            {'name': 'Pygame Basics',
             'programs': ['blankpygame.py', 'drawing.py', 'catanimation.py']},
            {'name': 'Memory Puzzle',
             'programs': ['memorypuzzle.py']},
            {'name': 'Slide Puzzle',
             'programs': ['slidepuzzle.py']},
            {'name': 'Simulate',
             'programs': ['simulate.py']},
            {'name': 'Wormy',
             'programs': ['wormy.py']},
            {'name': 'Tetromino',
             'programs': ['tetromino.py', 'pentomino.py', 'tetrominoforidiots.py'],
             'downloads': ['tetromino.zip']},
            {'name': 'Squirrel Eat Squirrel',
             'programs': ['squirrel.py'],
             'downloads': ['squirrel.zip']},
            {'name': 'Star Pusher',
             'programs': ['starpusher.py']},
            {'name': 'Four Extra Games',
             'programs': ['flippy.py', 'inkspill.py', 'fourinarow.py', 'gemgem.py'],
             'downloads': ['flippy.zip', 'inkspill.zip', 'fourinarow.zip', 'gemgem.zip']}]

hackingData = [{'name': 'Making Paper Cryptography Tools',
                'links': [{'PDF of the Caesar Cipher Wheel': 'http://inventwithpython.com/cipherwheel/cipherdisk_cutout_page.pdf'},
                          {'Interactive Virtual Cipher Wheel': 'http://inventwithpython.com/cipherwheel'}]},
            {'name': 'Downloading and Installing Python',
             'links': [{'Download Python 3': 'http://www.python.org/getit/'},
                       {'Download pyperclip.py': 'http://inventwithpython.com/pyperclip.py'}]},
            {'name': 'The Interactive Shell'},
            {'name': 'String and Writing Programs',
             'programs': ['hello.py']},
            {'name': 'The Reverse Cipher',
             'programs': ['reverseCipher.py']},
            {'name': 'The Caesar Cipher',
             'programs': ['caesarCipher.py', 'caesarCipher2.py', 'password.py', 'password2.py', 'elifeggs.py']},
            {'name': 'Hacking the Caesar Cipher with the Brute Force Technique',
             'programs': ['caesarHacker.py']},
            {'name': 'The Transposition Cipher, Encrypting',
             'programs': ['transpositionEncrypt.py']},
            {'name': 'The Transposition Cipher, Decrypting',
             'programs': ['transpositionDecrypt.py']},
            {'name': 'Programming a Program to Test Our Program',
             'programs': ['transpositionTest.py']},
            {'name': 'Encrypting and Decrypting Files',
             'programs': ['transpositionFileCipher.py']},
            {'name': 'Detecting English Programmatically',
             'programs': ['detectEnglish.py']},
            {'name': 'Hacking the Transposition Cipher',
             'programs': ['transpositionHacker.py']},
            {'name': 'Modular Arithmetic and the Multiplicative Cipher',
             'programs': ['cryptomath.py']},
            {'name': 'The Affine Cipher',
             'programs': ['affineCipher.py', 'affineKeyTest.py']},
            {'name': 'Hacking the Affine Cipher',
             'programs': ['affineHacker.py']},
            {'name': 'The Simple Substitution Cipher',
             'programs': ['simpleSubCipher.py']},
            {'name': 'Hacking the Simple Substitution Cipher',
             'programs': ['makeWordPatterns.py', 'wordPatterns.py', 'simpleSubHacker.py']},
            {'name': 'The Vigenère Cipher',
             'programs': ['vigenereCipher.py']},
            {'name': 'Frequency Analysis',
             'programs': ['freqAnalysis.py']},
            {'name': 'Hacking the Vigenère Cipher',
             'programs': ['vigenereHacker.py', 'vigenereDictionaryHacker.py']},
            {'name': 'The One-Time Pad Cipher'},
            {'name': 'Finding Prime Numbers',
             'programs': ['primeSieve.py', 'rabinMiller.py']},
            {'name': 'Public Key Cryptography and the RSA Cipher',
             'programs': ['makeRsaKeys.py', 'rsaCipher.py']}
            ]